"use server";

/**
 * CRM Server Actions
 *
 * All CRM-related database operations go through these server actions.
 * Pattern follows materials.ts: auth check → sanitize → DB → activity log → revalidate.
 */

import { revalidatePath } from "next/cache";
import { createClient, getUserRoleFromJWT } from "@/lib/supabase/server";
import { sanitizeText } from "@/lib/sanitize";
import { logActivity } from "@/lib/activity-log/actions";
import type {
  CrmBrand,
  CrmBrandWithStats,
  CrmArchitectureFirm,
  CrmContact,
  CrmContactWithRelations,
  CrmOpportunity,
  CrmOpportunityWithRelations,
  CrmActivity,
  CrmActivityWithRelations,
  CrmFirmWithLinks,
  CrmDashboardStats,
  OpportunityStage,
  PipelineColumn,
} from "@/types/crm";
import { OPPORTUNITY_STAGES } from "@/types/crm";

// ============================================================================
// Types
// ============================================================================

export interface ActionResult<T = void> {
  success: boolean;
  data?: T;
  error?: string;
}

// ============================================================================
// Auth Helpers
// ============================================================================

async function requireCrmAccess(requiredRoles: string[] = ["admin", "management"]) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Not authenticated" as const, supabase: null, user: null, role: null };
  }

  const role = await getUserRoleFromJWT(user, supabase);
  if (!requiredRoles.includes(role)) {
    return { error: "Not authorized" as const, supabase: null, user: null, role: null };
  }

  return { error: null, supabase, user, role };
}

// ============================================================================
// BRANDS
// ============================================================================

export async function getBrands(): Promise<ActionResult<CrmBrandWithStats[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    // Use the v_crm_brands view which pre-computes opportunity_count and
    // latest_activity_date via LEFT JOIN LATERAL — single query instead of N+1
    const { data, error: dbError } = await supabase!
      .from("v_crm_brands")
      .select("*")
      .order("priority", { ascending: true })
      .order("name", { ascending: true });

    if (dbError) return { success: false, error: dbError.message };

    return { success: true, data: (data || []) as unknown as CrmBrandWithStats[] };
  } catch (err) {
    console.error("getBrands error:", err);
    return { success: false, error: "Failed to fetch brands" };
  }
}

export async function getBrand(brandId: string): Promise<ActionResult<CrmBrand>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_brands")
      .select("*")
      .eq("id", brandId)
      .eq("is_deleted", false)
      .single();

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: data as CrmBrand };
  } catch (err) {
    console.error("getBrand error:", err);
    return { success: false, error: "Failed to fetch brand" };
  }
}

export async function createBrand(
  input: Record<string, unknown>
): Promise<ActionResult<{ id: string }>> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized = {
      name: sanitizeText((input.name as string).trim()),
      parent_group: input.parent_group ? sanitizeText((input.parent_group as string).trim()) : null,
      tier: input.tier as string,
      segment: input.segment ? sanitizeText((input.segment as string).trim()) : null,
      store_count: input.store_count as number | null,
      expansion_rate: input.expansion_rate ? sanitizeText((input.expansion_rate as string).trim()) : null,
      creative_director: input.creative_director ? sanitizeText((input.creative_director as string).trim()) : null,
      cd_changed_recently: input.cd_changed_recently as boolean,
      headquarters: input.headquarters ? sanitizeText((input.headquarters as string).trim()) : null,
      website: input.website || null,
      annual_revenue: input.annual_revenue ? sanitizeText((input.annual_revenue as string).trim()) : null,
      notes: input.notes ? sanitizeText((input.notes as string).trim()) : null,
      priority: input.priority as string,
    };

    // brand_code is auto-generated by BEFORE INSERT trigger (set_crm_brand_code)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error: dbError } = await supabase!
      .from("crm_brands")
      .insert(sanitized as any)
      .select("id")
      .single();

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_brand_created",
      entityType: "crm_brand",
      entityId: data.id,
      details: { name: sanitized.name },
    });

    revalidatePath("/crm");
    return { success: true, data: { id: data.id } };
  } catch (err) {
    console.error("createBrand error:", err);
    return { success: false, error: "Failed to create brand" };
  }
}

export async function updateBrand(
  brandId: string,
  input: Record<string, unknown>
): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized: Record<string, unknown> = {};
    if (input.name !== undefined) sanitized.name = sanitizeText((input.name as string).trim());
    if (input.parent_group !== undefined) sanitized.parent_group = input.parent_group ? sanitizeText((input.parent_group as string).trim()) : null;
    if (input.tier !== undefined) sanitized.tier = input.tier;
    if (input.segment !== undefined) sanitized.segment = input.segment ? sanitizeText((input.segment as string).trim()) : null;
    if (input.store_count !== undefined) sanitized.store_count = input.store_count;
    if (input.expansion_rate !== undefined) sanitized.expansion_rate = input.expansion_rate ? sanitizeText((input.expansion_rate as string).trim()) : null;
    if (input.creative_director !== undefined) sanitized.creative_director = input.creative_director ? sanitizeText((input.creative_director as string).trim()) : null;
    if (input.cd_changed_recently !== undefined) sanitized.cd_changed_recently = input.cd_changed_recently;
    if (input.headquarters !== undefined) sanitized.headquarters = input.headquarters ? sanitizeText((input.headquarters as string).trim()) : null;
    if (input.website !== undefined) sanitized.website = input.website || null;
    if (input.annual_revenue !== undefined) sanitized.annual_revenue = input.annual_revenue ? sanitizeText((input.annual_revenue as string).trim()) : null;
    if (input.notes !== undefined) sanitized.notes = input.notes ? sanitizeText((input.notes as string).trim()) : null;
    if (input.priority !== undefined) sanitized.priority = input.priority;

    const { error: dbError } = await supabase!
      .from("crm_brands")
      .update(sanitized as any) // eslint-disable-line @typescript-eslint/no-explicit-any
      .eq("id", brandId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_brand_updated",
      entityType: "crm_brand",
      entityId: brandId,
      details: { name: sanitized.name },
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("updateBrand error:", err);
    return { success: false, error: "Failed to update brand" };
  }
}

export async function deleteBrand(brandId: string): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const { error: dbError } = await supabase!
      .from("crm_brands")
      .update({ is_deleted: true })
      .eq("id", brandId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_brand_deleted",
      entityType: "crm_brand",
      entityId: brandId,
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("deleteBrand error:", err);
    return { success: false, error: "Failed to delete brand" };
  }
}

// ============================================================================
// BRAND RELATIONS (for detail page)
// ============================================================================

export interface BrandOpportunityRow {
  id: string;
  opportunity_code: string;
  title: string;
  stage: string;
  estimated_value: number | null;
  currency: string;
  priority: string;
}

export interface BrandActivityRow {
  id: string;
  activity_type: string;
  title: string;
  activity_date: string;
  outcome: string | null;
}

export async function getBrandOpportunities(
  brandId: string
): Promise<ActionResult<BrandOpportunityRow[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_opportunities")
      .select("id, opportunity_code, title, stage, estimated_value, currency, priority")
      .eq("brand_id", brandId)
      .eq("is_deleted", false)
      .order("created_at", { ascending: false })
      .limit(20);

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: (data ?? []) as unknown as BrandOpportunityRow[] };
  } catch (err) {
    console.error("getBrandOpportunities error:", err);
    return { success: false, error: "Failed to fetch brand opportunities" };
  }
}

export async function getBrandActivities(
  brandId: string
): Promise<ActionResult<BrandActivityRow[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_activities")
      .select("id, activity_type, title, activity_date, outcome")
      .eq("brand_id", brandId)
      .eq("is_deleted", false)
      .order("activity_date", { ascending: false })
      .limit(10);

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: (data ?? []) as unknown as BrandActivityRow[] };
  } catch (err) {
    console.error("getBrandActivities error:", err);
    return { success: false, error: "Failed to fetch brand activities" };
  }
}

// ============================================================================
// ARCHITECTURE FIRMS
// ============================================================================

export async function getArchitectureFirms(): Promise<ActionResult<CrmFirmWithLinks[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_architecture_firms")
      .select(`
        *,
        crm_brand_firm_links(
          relationship_type,
          brand:crm_brands(id, name, brand_code)
        )
      `)
      .eq("is_deleted", false)
      .order("priority", { ascending: true })
      .order("name", { ascending: true });

    if (dbError) return { success: false, error: dbError.message };

    // Transform the joined data to match CrmFirmWithLinks shape
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const firms = (data || []).map((f: any) => ({
      ...f,
      brand_links: (f.crm_brand_firm_links || []).map(
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        (l: any) => ({
          brand: l.brand as { id: string; name: string; brand_code: string },
          relationship_type: l.relationship_type as string | null,
        })
      ),
      crm_brand_firm_links: undefined,
    })) as CrmFirmWithLinks[];

    return { success: true, data: firms };
  } catch (err) {
    console.error("getArchitectureFirms error:", err);
    return { success: false, error: "Failed to fetch firms" };
  }
}

export async function getArchitectureFirm(firmId: string): Promise<ActionResult<CrmArchitectureFirm>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_architecture_firms")
      .select("*")
      .eq("id", firmId)
      .eq("is_deleted", false)
      .single();

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: data as CrmArchitectureFirm };
  } catch (err) {
    console.error("getArchitectureFirm error:", err);
    return { success: false, error: "Failed to fetch firm" };
  }
}

export async function createArchitectureFirm(
  input: Record<string, unknown>
): Promise<ActionResult<{ id: string }>> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized = {
      name: sanitizeText((input.name as string).trim()),
      location: input.location ? sanitizeText((input.location as string).trim()) : null,
      specialty: input.specialty ? sanitizeText((input.specialty as string).trim()) : null,
      key_clients: input.key_clients ? sanitizeText((input.key_clients as string).trim()) : null,
      vendor_list_status: input.vendor_list_status as string,
      vendor_application_date: input.vendor_application_date || null,
      website: input.website || null,
      connection_strength: input.connection_strength as string,
      connection_notes: input.connection_notes ? sanitizeText((input.connection_notes as string).trim()) : null,
      notes: input.notes ? sanitizeText((input.notes as string).trim()) : null,
      priority: input.priority as string,
    };

    // firm_code is auto-generated by BEFORE INSERT trigger (set_crm_firm_code)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error: dbError } = await supabase!
      .from("crm_architecture_firms")
      .insert(sanitized as any)
      .select("id")
      .single();

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_firm_created",
      entityType: "crm_firm",
      entityId: data.id,
      details: { name: sanitized.name },
    });

    revalidatePath("/crm");
    return { success: true, data: { id: data.id } };
  } catch (err) {
    console.error("createArchitectureFirm error:", err);
    return { success: false, error: "Failed to create firm" };
  }
}

export async function updateArchitectureFirm(
  firmId: string,
  input: Record<string, unknown>
): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized: Record<string, unknown> = {};
    if (input.name !== undefined) sanitized.name = sanitizeText((input.name as string).trim());
    if (input.location !== undefined) sanitized.location = input.location ? sanitizeText((input.location as string).trim()) : null;
    if (input.specialty !== undefined) sanitized.specialty = input.specialty ? sanitizeText((input.specialty as string).trim()) : null;
    if (input.key_clients !== undefined) sanitized.key_clients = input.key_clients ? sanitizeText((input.key_clients as string).trim()) : null;
    if (input.vendor_list_status !== undefined) sanitized.vendor_list_status = input.vendor_list_status;
    if (input.vendor_application_date !== undefined) sanitized.vendor_application_date = input.vendor_application_date || null;
    if (input.website !== undefined) sanitized.website = input.website || null;
    if (input.connection_strength !== undefined) sanitized.connection_strength = input.connection_strength;
    if (input.connection_notes !== undefined) sanitized.connection_notes = input.connection_notes ? sanitizeText((input.connection_notes as string).trim()) : null;
    if (input.notes !== undefined) sanitized.notes = input.notes ? sanitizeText((input.notes as string).trim()) : null;
    if (input.priority !== undefined) sanitized.priority = input.priority;

    const { error: dbError } = await supabase!
      .from("crm_architecture_firms")
      .update(sanitized as any) // eslint-disable-line @typescript-eslint/no-explicit-any
      .eq("id", firmId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_firm_updated",
      entityType: "crm_firm",
      entityId: firmId,
      details: { name: sanitized.name },
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("updateArchitectureFirm error:", err);
    return { success: false, error: "Failed to update firm" };
  }
}

export async function updateVendorStatus(
  firmId: string,
  status: string
): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const update: Record<string, unknown> = { vendor_list_status: status };
    if (status === "applied") {
      update.vendor_application_date = new Date().toISOString().split("T")[0];
    }

    const { error: dbError } = await supabase!
      .from("crm_architecture_firms")
      .update(update)
      .eq("id", firmId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_vendor_status_updated",
      entityType: "crm_firm",
      entityId: firmId,
      details: { vendor_list_status: status },
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("updateVendorStatus error:", err);
    return { success: false, error: "Failed to update vendor status" };
  }
}

// ============================================================================
// CONTACTS
// ============================================================================

export async function getContacts(): Promise<ActionResult<CrmContactWithRelations[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_contacts")
      .select(`
        *,
        brand:crm_brands(name, brand_code),
        architecture_firm:crm_architecture_firms(name, firm_code)
      `)
      .eq("is_deleted", false)
      .order("created_at", { ascending: false });

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: data as unknown as CrmContactWithRelations[] };
  } catch (err) {
    console.error("getContacts error:", err);
    return { success: false, error: "Failed to fetch contacts" };
  }
}

export async function createContact(
  input: Record<string, unknown>
): Promise<ActionResult<{ id: string }>> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized = {
      first_name: sanitizeText((input.first_name as string).trim()),
      last_name: sanitizeText((input.last_name as string).trim()),
      title: input.title ? sanitizeText((input.title as string).trim()) : null,
      company: input.company ? sanitizeText((input.company as string).trim()) : null,
      email: input.email || null,
      phone: input.phone ? sanitizeText((input.phone as string).trim()) : null,
      linkedin_url: input.linkedin_url || null,
      brand_id: input.brand_id || null,
      architecture_firm_id: input.architecture_firm_id || null,
      relationship_status: input.relationship_status as string,
      source: input.source ? sanitizeText((input.source as string).trim()) : null,
      notes: input.notes ? sanitizeText((input.notes as string).trim()) : null,
    };

    // contact_code is auto-generated by BEFORE INSERT trigger (set_crm_contact_code)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error: dbError } = await supabase!
      .from("crm_contacts")
      .insert(sanitized as any)
      .select("id")
      .single();

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_contact_created",
      entityType: "crm_contact",
      entityId: data.id,
      details: { name: `${sanitized.first_name} ${sanitized.last_name}` },
    });

    revalidatePath("/crm");
    return { success: true, data: { id: data.id } };
  } catch (err) {
    console.error("createContact error:", err);
    return { success: false, error: "Failed to create contact" };
  }
}

export async function updateContact(
  contactId: string,
  input: Record<string, unknown>
): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized: Record<string, unknown> = {};
    if (input.first_name !== undefined) sanitized.first_name = sanitizeText((input.first_name as string).trim());
    if (input.last_name !== undefined) sanitized.last_name = sanitizeText((input.last_name as string).trim());
    if (input.title !== undefined) sanitized.title = input.title ? sanitizeText((input.title as string).trim()) : null;
    if (input.company !== undefined) sanitized.company = input.company ? sanitizeText((input.company as string).trim()) : null;
    if (input.email !== undefined) sanitized.email = input.email || null;
    if (input.phone !== undefined) sanitized.phone = input.phone ? sanitizeText((input.phone as string).trim()) : null;
    if (input.linkedin_url !== undefined) sanitized.linkedin_url = input.linkedin_url || null;
    if (input.brand_id !== undefined) sanitized.brand_id = input.brand_id || null;
    if (input.architecture_firm_id !== undefined) sanitized.architecture_firm_id = input.architecture_firm_id || null;
    if (input.relationship_status !== undefined) sanitized.relationship_status = input.relationship_status;
    if (input.source !== undefined) sanitized.source = input.source ? sanitizeText((input.source as string).trim()) : null;
    if (input.notes !== undefined) sanitized.notes = input.notes ? sanitizeText((input.notes as string).trim()) : null;

    const { error: dbError } = await supabase!
      .from("crm_contacts")
      .update(sanitized as any) // eslint-disable-line @typescript-eslint/no-explicit-any
      .eq("id", contactId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_contact_updated",
      entityType: "crm_contact",
      entityId: contactId,
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("updateContact error:", err);
    return { success: false, error: "Failed to update contact" };
  }
}

// ============================================================================
// OPPORTUNITIES
// ============================================================================

export async function getOpportunities(): Promise<ActionResult<CrmOpportunityWithRelations[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_opportunities")
      .select(`
        *,
        brand:crm_brands(name, brand_code),
        architecture_firm:crm_architecture_firms(name, firm_code),
        assigned_user:users(name)
      `)
      .eq("is_deleted", false)
      .order("created_at", { ascending: false });

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: data as unknown as CrmOpportunityWithRelations[] };
  } catch (err) {
    console.error("getOpportunities error:", err);
    return { success: false, error: "Failed to fetch opportunities" };
  }
}

export async function getOpportunityPipeline(): Promise<ActionResult<PipelineColumn[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_opportunities")
      .select(`
        *,
        brand:crm_brands(name, brand_code),
        architecture_firm:crm_architecture_firms(name, firm_code),
        assigned_user:users(name)
      `)
      .eq("is_deleted", false)
      .order("priority", { ascending: true })
      .order("created_at", { ascending: false });

    if (dbError) return { success: false, error: dbError.message };

    const opportunities = data as unknown as CrmOpportunityWithRelations[];

    const columns: PipelineColumn[] = OPPORTUNITY_STAGES.map((stage) => ({
      stage: stage.value,
      label: stage.label,
      color: stage.color,
      opportunities: opportunities.filter((o) => o.stage === stage.value),
    }));

    return { success: true, data: columns };
  } catch (err) {
    console.error("getOpportunityPipeline error:", err);
    return { success: false, error: "Failed to fetch pipeline" };
  }
}

export async function createOpportunity(
  input: Record<string, unknown>
): Promise<ActionResult<{ id: string }>> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized = {
      title: sanitizeText((input.title as string).trim()),
      description: input.description ? sanitizeText((input.description as string).trim()) : null,
      brand_id: input.brand_id || null,
      architecture_firm_id: input.architecture_firm_id || null,
      stage: input.stage as string,
      estimated_value: input.estimated_value as number | null,
      currency: input.currency as string,
      probability: input.probability as number | null,
      expected_close_date: input.expected_close_date || null,
      assigned_to: input.assigned_to || null,
      source: input.source ? sanitizeText((input.source as string).trim()) : null,
      notes: input.notes ? sanitizeText((input.notes as string).trim()) : null,
      priority: input.priority as string,
    };

    // opportunity_code is auto-generated by BEFORE INSERT trigger (set_crm_opportunity_code)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error: dbError } = await supabase!
      .from("crm_opportunities")
      .insert(sanitized as any)
      .select("id")
      .single();

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_opportunity_created",
      entityType: "crm_opportunity",
      entityId: data.id,
      details: { title: sanitized.title, stage: sanitized.stage },
    });

    revalidatePath("/crm");
    return { success: true, data: { id: data.id } };
  } catch (err) {
    console.error("createOpportunity error:", err);
    return { success: false, error: "Failed to create opportunity" };
  }
}

export async function updateOpportunity(
  opportunityId: string,
  input: Record<string, unknown>
): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized: Record<string, unknown> = {};
    if (input.title !== undefined) sanitized.title = sanitizeText((input.title as string).trim());
    if (input.description !== undefined) sanitized.description = input.description ? sanitizeText((input.description as string).trim()) : null;
    if (input.brand_id !== undefined) sanitized.brand_id = input.brand_id || null;
    if (input.architecture_firm_id !== undefined) sanitized.architecture_firm_id = input.architecture_firm_id || null;
    if (input.stage !== undefined) sanitized.stage = input.stage;
    if (input.estimated_value !== undefined) sanitized.estimated_value = input.estimated_value;
    if (input.currency !== undefined) sanitized.currency = input.currency;
    if (input.probability !== undefined) sanitized.probability = input.probability;
    if (input.expected_close_date !== undefined) sanitized.expected_close_date = input.expected_close_date || null;
    if (input.assigned_to !== undefined) sanitized.assigned_to = input.assigned_to || null;
    if (input.source !== undefined) sanitized.source = input.source ? sanitizeText((input.source as string).trim()) : null;
    if (input.loss_reason !== undefined) sanitized.loss_reason = input.loss_reason ? sanitizeText((input.loss_reason as string).trim()) : null;
    if (input.notes !== undefined) sanitized.notes = input.notes ? sanitizeText((input.notes as string).trim()) : null;
    if (input.priority !== undefined) sanitized.priority = input.priority;

    const { error: dbError } = await supabase!
      .from("crm_opportunities")
      .update(sanitized as any) // eslint-disable-line @typescript-eslint/no-explicit-any
      .eq("id", opportunityId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_opportunity_updated",
      entityType: "crm_opportunity",
      entityId: opportunityId,
      details: sanitized,
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("updateOpportunity error:", err);
    return { success: false, error: "Failed to update opportunity" };
  }
}

export async function moveOpportunityStage(
  opportunityId: string,
  newStage: OpportunityStage
): Promise<ActionResult> {
  try {
    const { error, supabase } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    // Get current stage for logging
    const { data: current } = await supabase!
      .from("crm_opportunities")
      .select("stage, title")
      .eq("id", opportunityId)
      .single();

    const oldStage = current?.stage;

    const { error: dbError } = await supabase!
      .from("crm_opportunities")
      .update({ stage: newStage })
      .eq("id", opportunityId);

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_opportunity_stage_changed",
      entityType: "crm_opportunity",
      entityId: opportunityId,
      details: { old_stage: oldStage, new_stage: newStage, title: current?.title },
    });

    revalidatePath("/crm");
    return { success: true };
  } catch (err) {
    console.error("moveOpportunityStage error:", err);
    return { success: false, error: "Failed to move opportunity" };
  }
}

// ============================================================================
// ACTIVITIES
// ============================================================================

export async function getActivities(): Promise<ActionResult<CrmActivityWithRelations[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const { data, error: dbError } = await supabase!
      .from("crm_activities")
      .select(`
        *,
        brand:crm_brands(name),
        architecture_firm:crm_architecture_firms(name),
        contact:crm_contacts(first_name, last_name),
        opportunity:crm_opportunities(title),
        user:users(name)
      `)
      .eq("is_deleted", false)
      .order("activity_date", { ascending: false })
      .order("created_at", { ascending: false })
      .limit(100);

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: data as unknown as CrmActivityWithRelations[] };
  } catch (err) {
    console.error("getActivities error:", err);
    return { success: false, error: "Failed to fetch activities" };
  }
}

export async function createActivity(
  input: Record<string, unknown>
): Promise<ActionResult<{ id: string }>> {
  try {
    const { error, supabase, user } = await requireCrmAccess(["admin"]);
    if (error) return { success: false, error };

    const sanitized = {
      activity_type: input.activity_type as string,
      title: sanitizeText((input.title as string).trim()),
      description: input.description ? sanitizeText((input.description as string).trim()) : null,
      activity_date: input.activity_date as string,
      brand_id: input.brand_id || null,
      architecture_firm_id: input.architecture_firm_id || null,
      contact_id: input.contact_id || null,
      opportunity_id: input.opportunity_id || null,
      user_id: user!.id, // Auto-fill from auth context
      outcome: input.outcome ? sanitizeText((input.outcome as string).trim()) : null,
      next_action: input.next_action ? sanitizeText((input.next_action as string).trim()) : null,
      next_action_date: input.next_action_date || null,
    };

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error: dbError } = await supabase!
      .from("crm_activities")
      .insert(sanitized as any)
      .select("id")
      .single();

    if (dbError) return { success: false, error: dbError.message };

    await logActivity({
      action: "crm_activity_logged",
      entityType: "crm_activity",
      entityId: data.id,
      details: { title: sanitized.title, type: sanitized.activity_type },
    });

    revalidatePath("/crm");
    return { success: true, data: { id: data.id } };
  } catch (err) {
    console.error("createActivity error:", err);
    return { success: false, error: "Failed to create activity" };
  }
}

export async function getUpcomingActions(): Promise<ActionResult<CrmActivityWithRelations[]>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    const today = new Date().toISOString().split("T")[0];

    const { data, error: dbError } = await supabase!
      .from("crm_activities")
      .select(`
        *,
        brand:crm_brands(name),
        architecture_firm:crm_architecture_firms(name),
        contact:crm_contacts(first_name, last_name),
        opportunity:crm_opportunities(title),
        user:users(name)
      `)
      .eq("is_deleted", false)
      .not("next_action", "is", null)
      .gte("next_action_date", today)
      .order("next_action_date", { ascending: true })
      .limit(20);

    if (dbError) return { success: false, error: dbError.message };
    return { success: true, data: data as unknown as CrmActivityWithRelations[] };
  } catch (err) {
    console.error("getUpcomingActions error:", err);
    return { success: false, error: "Failed to fetch upcoming actions" };
  }
}

// ============================================================================
// DASHBOARD
// ============================================================================

export async function getCrmDashboardStats(): Promise<ActionResult<CrmDashboardStats>> {
  try {
    const { error, supabase } = await requireCrmAccess();
    if (error) return { success: false, error };

    // Parallel queries for dashboard stats
    const [brandsResult, firmsResult, oppsResult, actionsResult] = await Promise.all([
      supabase!.from("crm_brands").select("tier", { count: "exact" }).eq("is_deleted", false),
      supabase!.from("crm_architecture_firms").select("vendor_list_status", { count: "exact" }).eq("is_deleted", false),
      supabase!.from("crm_opportunities").select("stage, estimated_value, currency").eq("is_deleted", false),
      supabase!.from("crm_activities").select("next_action_date", { count: "exact" })
        .eq("is_deleted", false)
        .not("next_action", "is", null)
        .gte("next_action_date", new Date().toISOString().split("T")[0]),
    ]);

    const brands = brandsResult.data || [];
    const firms = firmsResult.data || [];
    const opps = oppsResult.data || [];

    // Calculate brand tier breakdown
    const brandsByTier = { luxury: 0, mid_luxury: 0, bridge: 0 };
    for (const b of brands) {
      if (b.tier in brandsByTier) brandsByTier[b.tier as keyof typeof brandsByTier]++;
    }

    // Vendor approved count
    const vendorApproved = firms.filter((f) => f.vendor_list_status === "approved").length;

    // Active opportunities (not won/lost)
    const activeOpps = opps.filter((o) => o.stage !== "won" && o.stage !== "lost");
    const totalPipelineValue = activeOpps.reduce(
      (sum, o) => sum + (Number(o.estimated_value) || 0),
      0
    );

    // Opportunities by stage
    const opportunitiesByStage: Record<OpportunityStage, number> = {
      researched: 0, contacted: 0, sample_sent: 0, meeting: 0,
      proposal: 0, negotiation: 0, won: 0, lost: 0,
    };
    for (const o of opps) {
      if (o.stage in opportunitiesByStage) opportunitiesByStage[o.stage as OpportunityStage]++;
    }

    return {
      success: true,
      data: {
        brandCount: brands.length,
        brandsByTier,
        firmCount: firms.length,
        vendorApproved,
        activeOpportunities: activeOpps.length,
        totalPipelineValue,
        pipelineCurrency: "USD",
        upcomingActions: actionsResult.count || 0,
        opportunitiesByStage,
      },
    };
  } catch (err) {
    console.error("getCrmDashboardStats error:", err);
    return { success: false, error: "Failed to fetch dashboard stats" };
  }
}
